name: Run CI Tests
on: [push]
env:
  GO_VERSION: ~1.19
jobs:
  changes:
    runs-on: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Check for changes
        run: |
          make changes
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
          - windows-2022
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.GO_VERSION}}
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
      - name: Run Go Test
        run: |
          make test
